name: Notify Discord on change

on:
  - push
  - create
  - delete
  - fork
  - issue_comment
  - issues
  - label
  - pull_request

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for jq availability in runner)
        uses: actions/checkout@v4

      - name: Prepare variables
        shell: bash
        run: |
          set -euo pipefail
          EVENT_JSON="$GITHUB_EVENT_PATH"

          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          BRANCH="${GITHUB_REF_NAME:-${{ github.ref_name }}}"

          # Get commits array length (0 if not push)
          COMMIT_COUNT=$(jq '.commits | length' "$EVENT_JSON")
          
          # Build commit list (hash + message)
          if [ "$COMMIT_COUNT" -gt 0 ]; then
            COMMITS_TEXT=$(jq -r '.commits[] | "\(.id[0:7]) \(.message)"' "$EVENT_JSON" | sed 's/"/\\"/g')
            LATEST_SHA=$(jq -r '.commits[-1].id' "$EVENT_JSON")
          else
            COMMITS_TEXT="No commits found for this event."
            LATEST_SHA=$(jq -r '.head_commit.id // .after // ""' "$EVENT_JSON")
          fi

          # Determine button URL (link to latest commit or repo)
          if [ -n "$LATEST_SHA" ] && [ "$LATEST_SHA" != "null" ]; then
            BUTTON_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/$LATEST_SHA"
          else
            BUTTON_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          fi

          # Author info (prefer commit author if available)
          COMMIT_AUTHOR_NAME="$(jq -r '.head_commit.author.name // ""' "$EVENT_JSON")"
          COMMIT_AUTHOR_USERNAME="$(jq -r '.head_commit.author.username // ""' "$EVENT_JSON")"
          if [ -n "$COMMIT_AUTHOR_NAME" ]; then
            AUTHOR="$COMMIT_AUTHOR_NAME"
          else
            AUTHOR="${{ github.actor }}"
          fi
          if [ -n "$COMMIT_AUTHOR_USERNAME" ]; then
            AUTHOR_USERNAME="$COMMIT_AUTHOR_USERNAME"
          else
            AUTHOR_USERNAME="${{ github.actor }}"
          fi
          AUTHOR_ICON="https://github.com/$AUTHOR_USERNAME.png"

          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "COMMITS_TEXT<<EOF" >> $GITHUB_ENV
          echo "$COMMITS_TEXT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "BUTTON_URL=$BUTTON_URL" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "AUTHOR_ICON=$AUTHOR_ICON" >> $GITHUB_ENV

      - name: Build payload with all commits
        run: |
          python3 - <<'PY' > payload.json
          import json, os
          import re

          commit_count = int(os.getenv("COMMIT_COUNT", "0"))
          commit_label = f"{commit_count} new commit" + ("" if commit_count == 1 else "s")
          repo_name = os.getenv("REPO_NAME", "")
          branch = os.getenv("BRANCH", "")
          commits_text = os.getenv("COMMITS_TEXT", "No commits found.")
          commit_url = os.getenv("BUTTON_URL", "")

          # Function to hyperlink commit hashes
          def hyperlink_hashes(text, url):
              # Match 7+ character hex hash at start of line
              lines = text.splitlines()
              new_lines = []
              for line in lines:
                  match = re.match(r'^([0-9a-f]{7,40})( .*)?$', line)
                  if match and url:
                      hash_part = match.group(1)
                      rest = match.group(2) or ""
                      new_lines.append(f"[{hash_part}]({url}) **|** {rest}")
                  else:
                      new_lines.append(line)
              return "\n".join(new_lines)

          description = hyperlink_hashes(commits_text, commit_url)

          title = f"[{repo_name}:{branch}] {commit_label}"

          payload = {
              "embeds": [
                  {
                      "author": {
                          "name": os.getenv("AUTHOR", ""),
                          "icon_url": os.getenv("AUTHOR_ICON", "")
                      },
                      "title": title,
                      "url": commit_url,
                      "description": description,
                      "color": 8022983
                  }
              ]
          }

          print(json.dumps(payload))
          PY



      - name: Send to Discord webhook
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }} # no error here btw
        run: |
          if [ -z "${WEBHOOK:-}" ]; then
            echo "Missing DISCORD_WEBHOOK_URL secret" >&2
            exit 1
          fi
          http_status=$(curl -sS -X POST \
            -H "Content-Type: application/json" \
            --data-binary @payload.json \
            "$WEBHOOK" -w "%{http_code}" -o /tmp/discord_resp.txt) || true
          echo "Discord response (body):"
          if [ -s /tmp/discord_resp.txt ]; then
            cat /tmp/discord_resp.txt || true
          else
            echo "(no body)"
          fi
          echo "HTTP status: $http_status"
          if [ "$http_status" -ge 400 ]; then
            exit 1
          fi
